### ISSUE TITLE
Whitespace displayed after apostrophe

### ISSUE THREAD

**Issue by sydbarrett74** [md-reader/md-reader#37]
Firstly, thank you for offering this extension. 😊

I opened a Markdown file, and it seems there's whitespace after all apostrophes. My copy of Chrome is 108.0.5359.125 x64 on Windows 11 10.0.22621.963 x64.

I've attached both the .md file in question and a screenshot of the rendered Markdown in a Chrome tab.

Please don't hesitate to ask if you need me to provide more information. Thank you for your time, and for continuing to maintain this piece of software.

![whitespace example](https://user-images.githubusercontent.com/6467403/210725218-57ccd404-ac36-48e8-9b98-8832486b147c.png)

[README.md](https://github.com/md-reader/md-reader/files/10350201/README.md)

**Comment by Heroor** [comment]
Thank you for using md-reader

After my check, the reason is that markdown-it configured typographer to render the quotation marks into printing format. Since md-reader set the font of the web page, windows rendered it as Microsoft Yahei according to the font priority, leading to the style of space in the quotation marks. I'll adjust the font order and release a fix

**Comment by Heroor** [comment]
Hi! Just wanted to thank you for your support, there’s a gift waiting for you — please leave your email here so we can send it over 🎁

— Bener, Markdown Reader
